INSERT INTO collection_point (city, name, address) VALUES ('Bắc Giang', 'Điểm tập kết Bắc Giang', 'KDC thôn Mỹ Cầu, cạnh đường Thân Nhân Trung, Tân Mỹ, TP Bắc Giang');
INSERT INTO collection_point (city, name, address) VALUES ('Bắc Kạn', 'Điểm tập kết Bắc Kạn', '74 Tổ 1 Sông Cầu, Tp Bắc Cạn');
INSERT INTO collection_point (city, name, address) VALUES ('Bắc Ninh', 'Điểm tập kết Bắc Ninh', 'Số Nhà 97C, Phố Vũ, Đường Trần Hưng Đạo. P. Đại Phúc, Tỉnh Bắc Ninh');
INSERT INTO collection_point (city, name, address) VALUES ('Cao Bằng', 'Điểm tập kết Cao Bằng', 'Số Nhà B012 Tổ 11, Phường Sông Hiến, Tp Cao Bằng');
INSERT INTO collection_point (city, name, address) VALUES ('Điện Biên', 'Điểm tập kết Điện Biên', 'Tổ 10 Phường Him Lam Tp Điện Biên(Cách Cổng Chào 100M)');
INSERT INTO collection_point (city, name, address) VALUES ('Hà Giang', 'Điểm tập kết Hà Giang', 'Số Nhà 33 Nguyễn Văn Cừ, Thành Phố Hà Giang, Tỉnh Hà Giang');
INSERT INTO collection_point (city, name, address) VALUES ('Hà Nam', 'Điểm tập kết Hà Nam', 'Số 32 Ngõ 131 Đường Đinh Tiên Hoàng Tổ 1 Trần Hưng Đạo Phủ L{ Hà Nam');
INSERT INTO collection_point (city, name, address) VALUES ('Hà Nội ', 'Điểm tập kết Hà Nội ', '57 Nguyễn Khang, Phường Yên Hòa, Quận Cầu Giấy, Tp Hà Nội');
INSERT INTO collection_point (city, name, address) VALUES ('Hà Tĩnh', 'Điểm tập kết Hà Tĩnh', 'Số 56 Đường Nguyễn Du Tp Hà Tĩnh , Tỉnh Hà Tĩnh');
INSERT INTO collection_point (city, name, address) VALUES ('Hải Dương', 'Điểm tập kết Hải Dương', 'Số 1A Trần Hưng Đạo, Thành Phố Hải Dương, Hải Dương');
INSERT INTO collection_point (city, name, address) VALUES ('Hải Phòng', 'Điểm tập kết Hải Phòng', '273 Trần Nguyên Hãn, P Nghĩa Xá, Q Lê Chân, Tp Hải Phòng');
INSERT INTO collection_point (city, name, address) VALUES ('Hòa Bình', 'Điểm tập kết Hòa Bình', 'Số 10 Ngách 6/85 Đường Lê Thánh Tông Phường Tân Thịnh Tp Hòa Bình');
INSERT INTO collection_point (city, name, address) VALUES ('Hưng Yên', 'Điểm tập kết Hưng Yên', 'Số 154 Phố Nối, Thị Trấn Bần, Xã Yên Nhân, Huyện Mỹ Hào,Tỉnh Hưng Yên');
INSERT INTO collection_point (city, name, address) VALUES ('Lai Châu', 'Điểm tập kết Lai Châu', 'Số 6, Ngõ 131 Đường Tràn Hưng Đạo, Phường Đoàn Kế, Tp Lai Châu');
INSERT INTO collection_point (city, name, address) VALUES ('Lạng Sơn', 'Điểm tập kết Lạng Sơn', 'Số 104 C Đường Lê Lợi, Khối 6, Phường Vĩnh Trại,Tp Lạng Sơn');
INSERT INTO collection_point (city, name, address) VALUES ('Lào Cai', 'Điểm tập kết Lào Cai', 'Số Nhà 106 Nguyễn Tri Phương, P. Phố Mới, Tp Lào Cai, Tỉnh Lào Cai');
INSERT INTO collection_point (city, name, address) VALUES ('Nam Định', 'Điểm tập kết Nam Định', 'Số 72B Tổ 11 (Sô 495) Đường Giải Phóng, Phường Trường Thi, Thành Phố Nam Định');
INSERT INTO collection_point (city, name, address) VALUES ('Nghệ An', 'Điểm tập kết Nghệ An', '159 Hà Huy Tập, Tp.Vinh, Tỉnh Nghệ An.');
INSERT INTO collection_point (city, name, address) VALUES ('Ninh Bình', 'Điểm tập kết Ninh Bình', '150 Đường Nguyễn Văn Cừ - Phố Vạn Xuân 1 – Phường Thanh Bình – Thành Phố Ninh Bình, Tỉnh Ninh Bình');
INSERT INTO collection_point (city, name, address) VALUES ('Phú Thọ', 'Điểm tập kết Phú Thọ', '72 Phố Hai Bà Trưng, P. Thọ Sơn, Tp. Việt Trì, Tỉnh Phú Thọ ');
INSERT INTO collection_point (city, name, address) VALUES ('Quảng Ninh', 'Điểm tập kết Quảng Ninh', 'Số 519 Nguyễn Văn Cừ, P. Hồng Hải, Tp.Hạ Long, Tỉnh Quảng Ninh');
INSERT INTO collection_point (city, name, address) VALUES ('Sơn La', 'Điểm tập kết Sơn La', 'Số Nhà 35, Tổ 3, Phường Quyết Thắng Tp Sơn La, Tỉnh Sơn La');
INSERT INTO collection_point (city, name, address) VALUES ('Thái Bình', 'Điểm tập kết Thái Bình', 'Số 66A, Ngô Thị Nhậm, P. Quang Trung, Tp Thái Bình, Tỉnh Thái Bình');
INSERT INTO collection_point (city, name, address) VALUES ('Thái Nguyên', 'Điểm tập kết Thái Nguyên', 'Số 416 Phan Đình Phùng, Tp Thái Nguyên, Tỉnh Thái Nguyên');
INSERT INTO collection_point (city, name, address) VALUES ('Thanh Hóa', 'Điểm tập kết Thanh Hóa', '663 Đường Bà Triệu, Phường Đông Thọ, TP. Thanh Hóa');
INSERT INTO collection_point (city, name, address) VALUES ('Tuyên Quang', 'Điểm tập kết Tuyên Quang', 'Số 08 Tổ 19 Trần Phú, Phường Tân Quang, Tp Tuyên Quang');
INSERT INTO collection_point (city, name, address) VALUES ('Vĩnh Phúc', 'Điểm tập kết Vĩnh Phúc', 'Số 572 Đình Ấm, Khai Quang, Tp. Vĩnh Yên, Tỉnh Vĩnh Phúc');
INSERT INTO collection_point (city, name, address) VALUES ('Yên Bái', 'Điểm tập kết Yên Bái', 'Số Nhà 28 Đường Thanh Niên Tổ 5A Hồng Phú Phường Hồng Hà Tp Yên Bái');
INSERT INTO collection_point (city, name, address) VALUES ('An Giang', 'Điểm tập kết An Giang', '55 Hai Bà Trưng, Khóm 5, P. Mỹ Long, Tp. Long Xuyên, Tỉnh An Giang');
INSERT INTO collection_point (city, name, address) VALUES ('Bà Rịa - Vũng Tàu', 'Điểm tập kết Bà Rịa Vũng Tàu', 'Số 353 Thống Nhất, Phường 08, Tp Vũng Tàu, Tỉnh Bà Rịa - Vũng Tàu');
INSERT INTO collection_point (city, name, address) VALUES ('Bạc Liêu', 'Điểm tập kết Bạc Liêu', 'Số 74/5 Tôn Đức Thắng, Khóm 5, Phường 07, Thành Phố Bạc Liêu, Tỉnh Bạc Liêu');
INSERT INTO collection_point (city, name, address) VALUES ('Bến Tre', 'Điểm tập kết Bến Tre', 'Số 06/B8 Đoàn Hoàng Minh,Khu Phố 4, Phường Phú Khương, Tỉnh Bến Tre');
INSERT INTO collection_point (city, name, address) VALUES ('Bình Định', 'Điểm tập kết Bình Định', 'Lô Số 7 Khu An Phú, Đường Tây Sơn, Phường Quang Trung, Tp Quy Nhơn, Tỉnh Bình Định');
INSERT INTO collection_point (city, name, address) VALUES ('Bình Dương', 'Điểm tập kết Bình Dương', '239, Quốc Lộ 1K, Linh Xuân, Thủ Đức, Tp. Hcm');
INSERT INTO collection_point (city, name, address) VALUES ('Bình Phước', 'Điểm tập kết Bình Phước', '94 Võ Văn Tần, P.Tân Bình, Tp Đồng Xoài , Bình Phước');
INSERT INTO collection_point (city, name, address) VALUES ('Bình Thuận', 'Điểm tập kết Bình Thuận', 'Số 300, Đường 19/4, P. Xuân An');
INSERT INTO collection_point (city, name, address) VALUES ('Cà Mau', 'Điểm tập kết Cà Mau', '51/57 Lý Thường Kiệt, Khóm 4, Phường 6, Tp. Cà Mau');
INSERT INTO collection_point (city, name, address) VALUES ('Cần Thơ', 'Điểm tập kết Cần Thơ', '88/8 Đường Lê Hồng Phong, Phường Trà Nóc, Quận Bình Thủy, Thành Phố Cần Thơ');
INSERT INTO collection_point (city, name, address) VALUES ('Đà Nẵng', 'Điểm tập kết Đà Nẵng', '26 Nguyễn Tri Phương, Phường Chính Gián');
INSERT INTO collection_point (city, name, address) VALUES ('Đắk Nông', 'Điểm tập kết Đắk Nông', '68 Quang Trung, Phường Nghĩa Tân');
INSERT INTO collection_point (city, name, address) VALUES ('Đắk Lắk', 'Điểm tập kết Đăklak', '25 Nguyễn Đình Chiểu, Phường Thắng Lợi, Tp. Buôn Ma Thuật, Tỉnh Đăk Lăk');
INSERT INTO collection_point (city, name, address) VALUES ('Đồng Nai', 'Điểm tập kết Đồng Nai', 'Số 1 ,Đường Số 1, Kcn Biên Hòa 1, Biên Hòa Đồng Nai');
INSERT INTO collection_point (city, name, address) VALUES ('Đồng Tháp', 'Điểm tập kết Đồng Tháp', 'Số 115 Đường Lê Anh Xuân, Phường 2, Tp.Cao Lãnh , Tỉnh Đồng Tháp');
INSERT INTO collection_point (city, name, address) VALUES ('Gia Lai', 'Điểm tập kết Gia Lai', 'Số 32 Lê Thánh Tôn, Phường Ia Kring, Tp.Pleiku, Tỉnh Gia Lai');
INSERT INTO collection_point (city, name, address) VALUES ('Hậu Giang', 'Điểm tập kết Hậu Giang', '59 Ngô Quốc Trị, Kv3, Phường 5, Tp. Vị Thanh, Hậu Giang');
INSERT INTO collection_point (city, name, address) VALUES ('TP. Hồ Chí Minh', 'Điểm tập kết Hồ Chí Minh', 'Số 239 Quốc Lộ 1K, Phường Linh Xuân, Quận Thủ Đức, Tp. Hcm');
INSERT INTO collection_point (city, name, address) VALUES ('Khánh Hòa', 'Điểm tập kết Khánh Hòa', '58A Trần Khánh Dư, P.Phước Tân');
INSERT INTO collection_point (city, name, address) VALUES ('Kiên Giang', 'Điểm tập kết Kiên Giang', '734 Nguyễn Trung Trực, P. An Hòa, Tp. Rạch Giá, Kiên Giang');
INSERT INTO collection_point (city, name, address) VALUES ('Kon Tum', 'Điểm tập kết Kon Tum', '869 Phan Đình Phùng, P. Quang Trung');
INSERT INTO collection_point (city, name, address) VALUES ('Lâm Đồng', 'Điểm tập kết Lâm Đồng', '64 Nguyễn Công Trứ, Phường 8, Tp. Đà Lạt ');
INSERT INTO collection_point (city, name, address) VALUES ('Long An', 'Điểm tập kết Long An', 'Số 447 Quốc Lộ 1, Khu Phố Bình Quân 2, Phường 4, Tp. Tân An, Tỉnh Long An, Việt Nam');
INSERT INTO collection_point (city, name, address) VALUES ('Ninh Thuận', 'Điểm tập kết Ninh Thuận', 'Số 37C Lê Duẩn, Phường Đài Sơn, Tp. Phan Rang Tháp Chàm, Ninh Thuận');
INSERT INTO collection_point (city, name, address) VALUES ('Phú Yên', 'Điểm tập kết Phú Yên', 'Số 36 Trần Phú, Phường 2, Tuy Hoà, Phú Yên');
INSERT INTO collection_point (city, name, address) VALUES ('Quảng Bình', 'Điểm tập kết Quảng Bình', 'Lô 11 Nguyễn Tuân, Phường Tân An, Thành Phố Hội An, Tỉnh Quảng Nam');
INSERT INTO collection_point (city, name, address) VALUES ('Quảng Nam', 'Điểm tập kết Quảng Nam', 'Lô 11 Nguyễn Tuân, Phường Tân An, Thành Phố Hội An, Tỉnh Quảng Nam');
INSERT INTO collection_point (city, name, address) VALUES ('Quảng Ngãi', 'Điểm tập kết Quảng Ngãi', '292 Lê Lợi, Phường Chánh Lộ, Tỉnh Quảng Ngãi');
INSERT INTO collection_point (city, name, address) VALUES ('Quảng Trị', 'Điểm tập kết Quảng Trị', '18 Bùi Thị Xuân, Kp5, P.2');
INSERT INTO collection_point (city, name, address) VALUES ('Sóc Trăng', 'Điểm tập kết Sóc Trăng', '292 Phú Lợi, Khóm 3, Phường 2, Tp. Sóc Trăng, Tỉnh Sóc Trăng');
INSERT INTO collection_point (city, name, address) VALUES ('Tây Ninh', 'Điểm tập kết Tây Ninh', '502 Lạc Long Quân, Kp5, Phường 4, Thành Phố Tây Ninh');
INSERT INTO collection_point (city, name, address) VALUES ('Thừa Thiên Huế', 'Điểm tập kết Thừa Thiên Huế', '11 Trần Cao Vân, P.Vĩnh Ninh');
INSERT INTO collection_point (city, name, address) VALUES ('Tiền Giang', 'Điểm tập kết Tiền Giang', '359, Ấp Phước Hòa, Xã Phước Thạnh');
INSERT INTO collection_point (city, name, address) VALUES ('Trà Vinh', 'Điểm tập kết Trà Vinh', '108A, Đường Võ Nguyên Giáp, K9, Phường 7, Thành Phố Trà Vinh, Tỉnh Trà Vinh');
INSERT INTO collection_point (city, name, address) VALUES ('Vĩnh Long', 'Điểm tập kết Vĩnh Long', 'Số 69/4 Đường Phó Cơ Điều, Khóm 2, Phường 3, Thành Phố Vĩnh Long, Tỉnh Vĩnh Long');
