import { ROLES } from "@utils/roles";

exports.cp_managers = [
    {
    name: 'Bắc Giang',
    email: 'tkbacgiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Bắc Kạn',
    email: 'tkbackan@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Bắc Ninh',
    email: 'tkbacninh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Cao Bằng',
    email: 'tkcaobang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Điện Biên',
    email: 'tkdienbien@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Hà Giang',
    email: 'tkhagiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Hà Nam',
    email: 'tkhanam@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Hà Nội ',
    email: 'tkhanoi@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Hà Tĩnh',
    email: 'tkhatinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Hải Dương',
    email: 'tkhaiduong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Hải Phòng',
    email: 'tkhaiphong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Hòa Bình',
    email: 'tkhoabinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Hưng Yên',
    email: 'tkhungyen@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Lai Châu',
    email: 'tklaichau@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Lạng Sơn',
    email: 'tklangson@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Lào Cai',
    email: 'tklaocai@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Nam Định',
    email: 'tknamdinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Nghệ An',
    email: 'tknghean@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Ninh Bình',
    email: 'tkninhbinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Phú Thọ',
    email: 'tkphutho@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Quảng Ninh',
    email: 'tkquangninh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Sơn La',
    email: 'tksonla@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Thái Bình',
    email: 'tkthaibinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Thái Nguyên',
    email: 'tkthainguyen@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Thanh Hóa',
    email: 'tkthanhhoa@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Tuyên Quang',
    email: 'tktuyenquang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Vĩnh Phúc',
    email: 'tkvinhphuc@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Yên Bái',
    email: 'tkyenbai@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'An Giang',
    email: 'tkangiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Bà Rịa - Vũng Tàu',
    email: 'tkbariavungtau@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Bạc Liêu',
    email: 'tkbaclieu@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Bến Tre',
    email: 'tkbentre@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Bình Định',
    email: 'tkbinhdinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Bình Dương',
    email: 'tkbinhduong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Bình Phước',
    email: 'tkbinhphuoc@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Bình Thuận',
    email: 'tkbinhthuan@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Cà Mau',
    email: 'tkcamau@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Cần Thơ',
    email: 'tkcantho@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Đà Nẵng',
    email: 'tkdanang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Đắk Nông',
    email: 'tkdaknong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Đắk Lắk',
    email: 'tkdaklak@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Đồng Nai',
    email: 'tkdongnai@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Đồng Tháp',
    email: 'tkdongthap@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Gia Lai',
    email: 'tkgialai@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Hậu Giang',
    email: 'tkhaugiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'TP. Hồ Chí Minh',
    email: 'tkhochiminh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Khánh Hòa',
    email: 'tkkhanhhoa@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Kiên Giang',
    email: 'tkkiengiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Kon Tum',
    email: 'tkkontum@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Lâm Đồng',
    email: 'tklamdong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Long An',
    email: 'tklongan@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Ninh Thuận',
    email: 'tkninhthuan@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Phú Yên',
    email: 'tkphuyen@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Quảng Bình',
    email: 'tkquangbinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Quảng Nam',
    email: 'tkquangnam@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Quảng Ngãi',
    email: 'tkquangngai@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Quảng Trị',
    email: 'tkquangtri@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Sóc Trăng',
    email: 'tksoctrang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Tây Ninh',
    email: 'tktayninh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Thừa Thiên Huế',
    email: 'tkthuathienhue@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Tiền Giang',
    email: 'tktiengiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Trà Vinh',
    email: 'tktravinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
  {
    name: 'Vĩnh Long',
    email: 'tkvinhlong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_MANAGER,
  },
];