import { ROLES } from '@utils/roles.js';

exports.collection_staff = [
  {
    name: 'Nhân viên tập kết Bắc Giang',
    email: 'cs_bacgiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 1,
  },
  {
    name: 'Nhân viên tập kết Bắc Kạn',
    email: 'cs_backan@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 2,
  },
  {
    name: 'Nhân viên tập kết Bắc Ninh',
    email: 'cs_bacninh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 3,
  },
  {
    name: 'Nhân viên tập kết Cao Bằng',
    email: 'cs_caobang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 4,
  },
  {
    name: 'Nhân viên tập kết Điện Biên',
    email: 'cs_dienbien@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 5,
  },
  {
    name: 'Nhân viên tập kết Hà Giang',
    email: 'cs_hagiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 6,
  },
  {
    name: 'Nhân viên tập kết Hà Nam',
    email: 'cs_hanam@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 7,
  },
  {
    name: 'Nhân viên tập kết Hà Nội',
    email: 'cs_hanoi@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 8,
  },
  {
    name: 'Nhân viên tập kết Hà Tĩnh',
    email: 'cs_hatinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 9,
  },
  {
    name: 'Nhân viên tập kết Hải Dương',
    email: 'cs_haiduong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 10,
  },
  {
    name: 'Nhân viên tập kết Hải Phòng',
    email: 'cs_haiphong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 11,
  },
  {
    name: 'Nhân viên tập kết Hòa Bình',
    email: 'cs_hoabinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 12,
  },
  {
    name: 'Nhân viên tập kết Hưng Yên',
    email: 'cs_hungyen@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 13,
  },
  {
    name: 'Nhân viên tập kết Lai Châu',
    email: 'cs_laichau@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 14,
  },
  {
    name: 'Nhân viên tập kết Lạng Sơn',
    email: 'cs_langson@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 15,
  },
  {
    name: 'Nhân viên tập kết Lào Cai',
    email: 'cs_laocai@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 16,
  },
  {
    name: 'Nhân viên tập kết Nam Định',
    email: 'cs_namdinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 17,
  },
  {
    name: 'Nhân viên tập kết Nghệ An',
    email: 'cs_nghean@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 18,
  },
  {
    name: 'Nhân viên tập kết Ninh Bình',
    email: 'cs_ninhbinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 19,
  },
  {
    name: 'Nhân viên tập kết Phú Thọ',
    email: 'cs_phutho@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 20,
  },
  {
    name: 'Nhân viên tập kết Quảng Ninh',
    email: 'cs_quangninh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 21,
  },
  {
    name: 'Nhân viên tập kết Sơn La',
    email: 'cs_sonla@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 22,
  },
  {
    name: 'Nhân viên tập kết Thái Bình',
    email: 'cs_thaibinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 23,
  },
  {
    name: 'Nhân viên tập kết Thái Nguyên',
    email: 'cs_thainguyen@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 24,
  },
  {
    name: 'Nhân viên tập kết Thanh Hóa',
    email: 'cs_thanhhoa@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 25,
  },
  {
    name: 'Nhân viên tập kết Tuyên Quang',
    email: 'cs_tuyenquang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 26,
  },
  {
    name: 'Nhân viên tập kết Vĩnh Phúc',
    email: 'cs_vinhphuc@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 27,
  },
  {
    name: 'Nhân viên tập kết Yên Bái',
    email: 'cs_yenbai@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 28,
  },
  {
    name: 'Nhân viên tập kết An Giang',
    email: 'cs_angiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 29,
  },
  {
    name: 'Nhân viên tập kết Bà Rịa - Vũng Tàu',
    email: 'cs_baria-vungtau@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 30,
  },
  {
    name: 'Nhân viên tập kết Bạc Liêu',
    email: 'cs_baclieu@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 31,
  },
  {
    name: 'Nhân viên tập kết Bến Tre',
    email: 'cs_bentre@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 32,
  },
  {
    name: 'Nhân viên tập kết Bình Định',
    email: 'cs_binhdinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 33,
  },
  {
    name: 'Nhân viên tập kết Bình Dương',
    email: 'cs_binhduong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 34,
  },
  {
    name: 'Nhân viên tập kết Bình Phước',
    email: 'cs_binhphuoc@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 35,
  },
  {
    name: 'Nhân viên tập kết Bình Thuận',
    email: 'cs_binhthuan@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 36,
  },
  {
    name: 'Nhân viên tập kết Cà Mau',
    email: 'cs_camau@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 37,
  },
  {
    name: 'Nhân viên tập kết Cần Thơ',
    email: 'cs_cantho@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 38,
  },
  {
    name: 'Nhân viên tập kết Đà Nẵng',
    email: 'cs_danang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 39,
  },
  {
    name: 'Nhân viên tập kết Đắk Nông',
    email: 'cs_daknong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 40,
  },
  {
    name: 'Nhân viên tập kết Đắk Lắk',
    email: 'cs_daklak@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 41,
  },
  {
    name: 'Nhân viên tập kết Đồng Nai',
    email: 'cs_dongnai@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 42,
  },
  {
    name: 'Nhân viên tập kết Đồng Tháp',
    email: 'cs_dongthap@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 43,
  },
  {
    name: 'Nhân viên tập kết Gia Lai',
    email: 'cs_gialai@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 44,
  },
  {
    name: 'Nhân viên tập kết Hậu Giang',
    email: 'cs_haugiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 45,
  },
  {
    name: 'Nhân viên tập kết TP. Hồ Chí Minh',
    email: 'cs_tp.hochiminh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 46,
  },
  {
    name: 'Nhân viên tập kết Khánh Hòa',
    email: 'cs_khanhhoa@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 47,
  },
  {
    name: 'Nhân viên tập kết Kiên Giang',
    email: 'cs_kiengiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 48,
  },
  {
    name: 'Nhân viên tập kết Kon Tum',
    email: 'cs_kontum@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 49,
  },
  {
    name: 'Nhân viên tập kết Lâm Đồng',
    email: 'cs_lamdong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 50,
  },
  {
    name: 'Nhân viên tập kết Long An',
    email: 'cs_longan@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 51,
  },
  {
    name: 'Nhân viên tập kết Ninh Thuận',
    email: 'cs_ninhthuan@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 52,
  },
  {
    name: 'Nhân viên tập kết Phú Yên',
    email: 'cs_phuyen@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 53,
  },
  {
    name: 'Nhân viên tập kết Quảng Bình',
    email: 'cs_quangbinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 54,
  },
  {
    name: 'Nhân viên tập kết Quảng Nam',
    email: 'cs_quangnam@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 55,
  },
  {
    name: 'Nhân viên tập kết Quảng Ngãi',
    email: 'cs_quangngai@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 56,
  },
  {
    name: 'Nhân viên tập kết Quảng Trị',
    email: 'cs_quangtri@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 57,
  },
  {
    name: 'Nhân viên tập kết Sóc Trăng',
    email: 'cs_soctrang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 58,
  },
  {
    name: 'Nhân viên tập kết Tây Ninh',
    email: 'cs_tayninh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 59,
  },
  {
    name: 'Nhân viên tập kết Thừa Thiên Huế',
    email: 'cs_thuathienhue@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 60,
  },
  {
    name: 'Nhân viên tập kết Tiền Giang',
    email: 'cs_tiengiang@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 61,
  },
  {
    name: 'Nhân viên tập kết Trà Vinh',
    email: 'cs_travinh@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 62,
  },
  {
    name: 'Nhân viên tập kết Vĩnh Long',
    email: 'cs_vinhlong@boltz.com',
    password: '123',
    role: ROLES.COLLECTION_STAFF,
    collection_point_id: 63,
  },
];